---
- name: Test Vault credential and secret lookup
  hosts: localhost
  tasks:
    - name: Print Vault env vars
      ansible.builtin.debug:
        msg:
          - "{{ ansible_user }}"
          - "VaultPath {{ VaultPath }}"
          - "vault_path {{ vault_path }}"
      ignore_errors: true

    - name: Print Vault env vars
      ansible.builtin.debug:
        msg:
          - "VaultPath {{ VaultPath }}"
      ignore_errors: true

    - name: Print Vault env vars
      ansible.builtin.debug:
        msg:
          - "vault_path {{ vault_path }}"
      ignore_errors: true
