---
- name: Test Vault credential and secret lookup
  hosts: localhost
  vars:
    secret_key_name: ""
  tasks:
    - name: Print Vault env vars
      ansible.builtin.debug:
        msg:
          - "VAULT_ADDR: {{ lookup('env', 'VAULT_ADDR') }}"
          - "VAULT_ROLE_ID: {{ lookup('env', 'VAULT_ROLE_ID') }}"
          - "VAULT_SECRET_ID: {{ lookup('env', 'VAULT_SECRET_ID') }}"
          - "VAULT_TOKEN: {{ lookup('env', 'VAULT_TOKEN') | default('Not set', true) }}"
          - "key1 {{ key1 }}"
          - "secret_key_name {{ secret_key_name }}"
          - "mysecret {{ mysecret }}"

    - name: Fetch secret from Vault (KV v2)
      ansible.builtin.set_fact:
        mysecret_value: "{{ lookup('community.hashi_vault.hashi_vault', 'secret/data/mysecret:mykey') }}"

    - name: Print secret value
      ansible.builtin.debug:
        msg: "Fetched secret value: {{ mysecret_value }}"
