---
- name: Test Vault credential and secret lookup
  hosts: localhost
  tasks:
    - name: Print Vault env vars
      ansible.builtin.debug:
        msg:
          - "VAULT_ADDR: {{ lookup('env', 'VAULT_ADDR') }}"
          - "VAULT_ROLE_ID: {{ lookup('env', 'VAULT_ROLE_ID') }}"
          - "VAULT_SECRET_ID: {{ lookup('env', 'VAULT_SECRET_ID') }}"
          - "VAULT_TOKEN: {{ lookup('env', 'VAULT_TOKEN') | default('Not set', true) }}"

    - name: Fetch secret from Vault (KV v2)
      ansible.builtin.set_fact:
        mysecret_value: {{ lookup('community.hashi_vault.hashi_vault', 'secret/data/mysecret:mykey') }}

    - name: Print secret value
      ansible.builtin.debug:
        msg: "Fetched secret value: {{ mysecret_value }}"
