---
- name: Test the cloud.terraform_ops.plan_stash role (stash functionality)
  hosts: localhost
  gather_facts: true
  vars:
    terraform_existing_plan_url: ""
    plan_stash_var_name_val: my_test_stashed_plan
    plan_stash_generate_plan_file_name_val: ./myplan.tfplan
  tasks:

    - name: Download terraform plan file and store as "{{ plan_stash_generate_plan_file_name_val }}"
      uri:
          dest: "{{ plan_stash_generate_plan_file_name_val }}"
          url: "{{ terraform_existing_plan_url }}"
      when: terraform_existing_plan_url is defined and terraform_existing_plan_url | length != 0

    - name: Stash the Terraform plan file into variable "{{ plan_stash_var_name_val }}"
      ansible.builtin.include_role:
        name: cloud.terraform_ops.plan_stash
      vars:
        plan_stash_operation: stash
        plan_stash_var_name: "{{ plan_stash_var_name_val }}" # if not provided, defaults to "terraform_plan"
        plan_stash_plan_file_path: "{{ plan_stash_generate_plan_file_name_val }}"
