---
- name: Test the cloud.terraform_ops.plan_stash role (load functionality)
  hosts: localhost
  gather_facts: false
  vars:
    plan_stash_var_name_val: ""
    plan_stash_plan_file_path_val: ""
  tasks:
    - name: Create a gcs bucket for Terraform remote backend
      ansible.builtin.include_role:
        name: cloud.terraform_ops.plan_stash
      vars:
        plan_stash_operation: load
        plan_stash_var_name: "{{ plan_stash_var_name_val }}" # if not provided, defaults to "terraform_plan"
        plan_stash_plan_file_path: "{{ plan_stash_plan_file_path_val }}" #"path_to_my_plan_file"

    - name: Apply the Terraform configuration
      cloud.terraform.terraform:
        project_path: "./"
        force_init: true
        plan_file: "{{ plan_stash_plan_file_path_val }}"
        state: present