---
- name: Apply tf config to generate random string
  hosts: localhost
  gather_facts: true
  tasks:
    - name: Apply tf config
      cloud.terraform.terraform:
        project_path: "./"
        state: present
        force_init: true